name       : librest
version    : 0.8.0
release    : 7
source     :
    - http://ftp.gnome.org/pub/gnome/sources/rest/0.8/rest-0.8.0.tar.xz : e7b89b200c1417073aef739e8a27ff2ab578056c27796ec74f5886a5e0dff647
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : RESTful API library
description: |
    librest was designed to make it easier to access web services that claim to be "RESTful". It includes convenience wrappers for libsoup and libxml to ease remote use of the RESTful API.
emul32     : yes
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(libsoup-2.4)
    - pkgconfig32(libsoup-2.4)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(libxml-2.0)
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
