name        : librest
version     : 0.7.93
release     : 4
source     :
    - http://ftp.gnome.org/pub/gnome/sources/rest/0.7/rest-0.7.93.tar.xz : c710644455340a44ddc005c645c466f05c0d779993138ea21a62c6082108b216
license     : LGPL-2.1
summary     : RESTful API library
builddeps   :
    - pkgconfig(libsoup-2.4)
description : |
    librest was designed to make it easier to access web services that claim to be "RESTful". It includes convenience wrappers for libsoup and libxml to ease remote use of the RESTful API.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
